---
abstract: 'Maintain cluster of master and replica AnyEvent::DBD::mysql instances'
author:
  - 'Maxim Polyakov <mmonk@cpan.org>'
build_requires:
  AnyEvent: 0
  AnyEvent::DBD::mysql: 0
  Data::Dumper: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.76, CPAN::Meta::Converter version 2.132510'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-DBD-mysql-Cluster
no_index:
  directory:
    - t
    - inc
requires:
  AnyEvent: 0
  AnyEvent::DBD::mysql: 0
  perl: 5.006
version: 0.01
